apiVersion: v1
kind: PersistentVolume
metadata::
  name: ebs-static-pv 
spec:
  accessModes:
    - ReadWriteOnce
  capicity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-05d8a95c91dd4b1c1