apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  volumeName: ebs-static-pv 		
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    project: expense
    environmet: dev 
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      environmet: dev 
  template:
    metadata:
      name: my-pod
      labels: 
        project: expense
        environmet: dev
        service: lb-service
    spec:
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-static-pvc
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
