apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels:
    project: expense
    env: prod
spec:
  containers:
  - name: nginx-1
    image: nginx
    ports:
    - containerPort: 80
  - name: apache-container
    image: almalinux:9
    command: ["sleep", "200"]
    env:
    - name: project
      value: expense
    - name: environment
      value: dev

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    project: expense
    env: prod 
spec:
  selector:
    project: expense
    env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80