apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels:
    project: expense
    env: prod
spec:
  containers:
  - name: nginx-1
    image: nginx
    ports:
    - containerPort: 80
  - name: nginx-2
    image: nginx
    env:
    - name: project
      value: expense
    - name: environment
      value: dev

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc 
spec:
  selector:
    project: expense
    env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80