apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    component: web
    project: expense
  annotations:
    kubernetes.io/change-cause: Updated-image-to-nginx:1.0.2

spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
      project: expense
  template:
    metadata:
      name: deployment-pod
      labels:
        component: web
        project: expense
        connection: connect-lb-service
    spec:
      containers:
      - name: nginx
        image: naveenrajoli/deployment:1.0.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-lb
spec:
  type: LoadBalancer
  selector:
    connection: connect-lb-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31800