apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::343430925817:role/eksctl-rajolinaveen-nodegroup-expe-NodeInstanceRole-YVK6BM7dhDzD
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-reader
    username: naveenRBAC
    userarn: arn:aws:iam::343430925817:user/naveenRBAC
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::343430925817:role/eksctl-rajolinaveen-nodegroup-expe-NodeInstanceRole-YVK6BM7dhDzD\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUser":"- groups:\n  - expense-reader\nusername: naveenRBAC\nuserarn: arn:aws:iam::343430925817:user/naveenRBAC\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-07-12T09:33:48Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1333"}}
  creationTimestamp: "2025-07-12T09:33:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "9449"
 
