apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::343430925817:role/eksctl-rajolinaveen-nodegroup-expe-NodeInstanceRole-YVK6BM7dhDzD
      username: system:node:{{EC2PrivateDNSName}}
  
  mapUser: |
    - groups:
      - expense-reader
    username: naveenRBAC
    userarn: arn:aws:iam::343430925817:user/naveenRBAC
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-12T09:33:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1333"
 
